language: python
python:
    - "2.7"
sudo: false
cache:
    directories:
        - "~/.platformio"
install:
    - pip install -U platformio
    - platformio update
#    - platformio lib -g install ArduinoSTL
script:
    - platformio ci --lib="." --project-conf=examples/simple/platformio.ini examples/simple
    - platformio ci --lib="." --project-conf=examples/simple/platformio.ini examples/esp32
