language: python
python:
    - "2.7"
sudo: false
cache:
    directories:
        - "~/.platformio"
install:
    - pip install -U platformio
    - platformio update
script:
    - platformio ci --lib="." --board=pro8MHzatmega328 --project-option="lib_deps=ArduinoSTL" examples/simple
    - platformio ci --lib="." --board=heltec_wifi_lora_32 examples/esp32
