name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: |
          pip install --upgrade platformio
          platformio platform install native
      - name: Run unit test
        run: platformio test -e native
      - name: Build simple exemple
        run: platformio ci --lib="." --board=pro8MHzatmega328 --project-option="lib_deps=https://github.com/ngraziano/avr_stl.git" examples/simple
      - name: Build simple sx1262 exemple
        run: platformio ci --lib="." --board=pro8MHzatmega328 --project-option="lib_deps=https://github.com/ngraziano/avr_stl.git" examples/simple_sx1262
      - name: Build esp32 exemple
        run: platformio ci --lib="." --board=heltec_wifi_lora_32 examples/esp32
