name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
          # Workaround.
          pip install "click!=8.0.2"
      - name: Build simple exemple
        run: platformio ci --lib="." --board=pro8MHzatmega328 --project-option="lib_deps=ArduinoSTL" examples/simple
      - name: Build simple sx1262 exemple
        run: platformio ci --lib="." --board=pro8MHzatmega328 --project-option="lib_deps=ArduinoSTL" examples/simple_sx1262
      - name: Build esp32 exemple
        run: platformio ci --lib="." --board=heltec_wifi_lora_32 examples/esp32
