name: PlatformIO CI

on:
  release:
    types: [released]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: |
          pip install --upgrade platformio
      - name: Release
        env: # Or as an environment variable
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.PIO_TOKEN }}
        run: platformio package publish --non-interactive
